version: '3.8'

services:
  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy 
    volumes:
      - .:/code

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./datos.sql:/docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d myfirstdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: